
all: marxan_test

marxan_test:  
	g++ -O3 -std=c++17 main_test.cpp algorithms_test.cpp computation_test.cpp utils_test.cpp  ../algorithms.cpp ../computation.cpp ../utils.cpp -o test -lCppUTest -lCppUTestExt 
