
name: Build__macOS_x86_64

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out repository
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Install OpenMP
        run: brew install libomp
      - name: Crete bin directory
        run: mkdir bin
      - name: Build 
        run: |
          g++ *.cpp /usr/local/opt/libomp/lib/libomp.a -o bin/marxan -Xclang -fopenmp -std=c++17  -O3
      - name: Zip 
        run: |
          cd bin
          zip marxan-macOS-x86-64.zip marxan
          cd ..
      
      # Uploads build results to an artifact
      - uses: actions/upload-artifact@v2
        with:
          name: marxan-acOS-86-64
          path: bin/marxan-macOS-x86-64.zip
